[package]
name = "python_bindings"
version = "0.1.0"
edition = "2021"

[lib]
name = "rs_utils"
crate-type = ["cdylib"]

[dependencies]
pyo3 = {version = "0.19.0", features = ["anyhow", "chrono"]}
pythonize = "0.19"
utils = {path = "../utils"}
